### ISSUE TITLE
Why not take advantage of Keep-Alive?

### ISSUE THREAD

**Issue by kijin** [ktamas77/firebase-php#14]
`firebase-php` promptly closes the curl handle after each request, making it impossible to take advantage of the underlying protocol's Keep-Alive capability. Since all Firebase API requests use SSL, using Keep-Alive would save a massive amount of time and resources (SSL handshake in addition to TCP handshake) when multiple requests are made in quick succession.

Enabling Keep-Alive with PHP curl is as simple as reusing the same curl handle without closing it.

**Comment by ktamas77** [comment]
I agree, it's a nice improvement, please see my comment on https://github.com/ktamas77/firebase-php/pull/15 and https://github.com/ktamas77/firebase-php/pull/16
