### ISSUE TITLE
Install through composer

### ISSUE THREAD

**Issue by tems99** [ktamas77/firebase-php#17]
Hi,

I tried using your library and added it to my zf2 application using composer.
I added this line to my composer.json file

"ktamas77/firebase-php": "dev-master"

The library was successfully added to my zf2 application, but I can't call the Firebase class in the code. 
I tried the following
$fb = new Firebase($url, $token);
$fb = new \Firebase($url, $token);

Sorry for the newbie question, but how do I fix this?

**Comment by llbbl** [comment]
this also works:
require 'vendor/ktamas77/firebase-php/firebaseLib.php';

not the best solution

**Comment by ktamas77** [comment]
This issue is fixed with the latest update: https://github.com/ktamas77/firebase-php/pull/21
Thank you for your suggestions and comments.
