### ISSUE TITLE
_getJsonPath function doesn't allow query strings

### ISSUE THREAD

**Issue by solyoung** [ktamas77/firebase-php#19]
The Firebase API offers orderBy and advanced query options. The _getJsonPath function currently appends ".json" to the end of the path without regard to the $path. This should be corrected so that query strings can be passed in the $path.

I may fork and solve, but at least wanted the issue reported in case I don't get back here.

**Comment by markdrake** [comment]
I'm having the same issue as solyoung. I wanted to use the query options but as you hard code the auth variable as the only query param available you make it impossible to use this without modification. I know it's a very simple wrapper but a more dynamic params approach would be ideal.

**Comment by ktamas77** [comment]
Thank you for your suggestion, this is a very important feature. I marked it as a todo.

**Comment by reedgz** [comment]
I would love to see this feature as well.  Then we can use shallow copy and other query options.
`'https://samplechat.firebaseio-demo.com/.json?shallow=true'`

**Comment by solyoung** [comment]
Here's a suggestion that would allow query functionality to get through that function (it's how I have the code modified in the meantime):
    private function _getJsonPath($path)
    {
        $url = $this->_baseURI;
        $path = ltrim($path, '/');
        $qaToken = (strpos($path, '?') == FALSE) ? '?' : '&';
        $auth = ($this->_token == '') ? '' : $qaToken . 'auth=' . $this->_token;
        $incJSON = (strpos($path, '.json') == FALSE) ? '.json' : '';
        return $url . $path . $incJSON . $auth;
    }

**Comment by askinner2004** [comment]
I modified the firebaseLib.php file with the following lines to add some query functionality:
...
private $_options;
...
public function setOptions($options = NULL)
	{
		if($options !== NULL)
		{
			foreach($options as $f => $v)
			{
				$new_options[$f] = '"' . $v . '"';
			}
		} else {
			$new_options = $options;
		}
		$this->_options = $new_options;
	}
...
    private function _getJsonPath($path)
    {
        $url = $this->_baseURI;
        $path = ltrim($path, '/');
        $auth = ($this->_token == '') ? '' : 'auth=' . $this->_token;
		 if($this->_options != NULL) 
		 {
			 $data = http_build_query($this->_options);
			 $auth = "?". str_replace('%22','"',$data) . "&" . $auth;
		 } else {
			 $auth = "?" . $auth;
		 }
		 $new_url = $url . $path . '.json' . $auth;
        return $new_url; 
    }
---

**Comment by ktamas77** [comment]
Query parameters are supported in version v2.1.0

https://github.com/ktamas77/firebase-php/releases/tag/v2.1.0
