### ISSUE TITLE
Error in README.md document

### ISSUE THREAD

**Issue by reedgz** [ktamas77/firebase-php#22]
I tried to use the library as README.md, PHP can never load class "Firebase".
It turns out that there is no "Firebase" class.   I don't know how the other guys could even load it.

This one worked.

```php
$firebase = new \Firebase\FirebaseLib($DEFAULT_URL, $DEFAULT_TOKEN);
```

This one does not work

```php
$firebase = new Firebase(DEFAULT_URL, DEFAULT_TOKEN);
```

**Comment by lawlessmedia** [comment]
I had the same issue. Changing the class name per reedgz's example got it working for me as well.

**Comment by ktamas77** [comment]
This is fixed, thank you for your comment.
