### ISSUE TITLE
php not working on remote server

### ISSUE THREAD

**Issue by saffabook** [ktamas77/firebase-php#26]
Hi

This might seem a stupid question but I am really stumped.

I have the code on my local server and it works fantastically. The local writes out to firebase, my app picks it up nicely etc. Works as expected. 

However, when I upload it to my remote server, which is an exact mirror, it all seems to break. In my error logs it says 
PHP Fatal error:  Class 'Firebase\\FirebaseLib' not found in..... 

Is there a way to install this manually, rather than composer? I am very unfamiliar with composer. 

Best regards

**Comment by saffabook** [comment]
Hi I found the error, it is case sensitive issue, the files in the source needed to start with Caps for unix setup.

**Comment by andazlan** [comment]
still class not found...
