### ISSUE TITLE
Can't use Query string with get method

### ISSUE THREAD

**Issue by bangank36** [ktamas77/firebase-php#31]
Hi,
I've used the "get" method to retrieve query data, but it seem didn't work, the error is:
{ "error" : "Constraint index field must be a JSON primitive" }
Pls note that if I put the URL on address bar, I still can get the matched data
https://goldenmuse.firebaseio.com/user.json?orderBy="email"&startAt="ba@gmail.com"&endAt="ba@gmail.com"
Could anyone help me resolve this?
Thanks.

Related issue: https://github.com/ktamas77/firebase-php/issues/19
Related PR: https://github.com/ktamas77/firebase-php/pull/25/files

**Comment by ktamas77** [comment]
Query strings are now supported in v2.1.0

https://github.com/ktamas77/firebase-php/releases/tag/v2.1.0

**Comment by WilliamCampolina** [comment]
Good afternoon, I downloaded the version 'v2.1.0' and continued giving the same message, could you help me?

**Comment by joseSantacruz** [comment]
I have the same error usin exactly emails on startat and endat

**Comment by aghiecool** [comment]
I had to modify "firebaseLib.php" and add these lines:

`
private function _getJsonPath($path)

    {
        $url = $this->_baseURI;
        $path = ltrim($path, '/');
        $auth = ($this->_token == '') ? '' : '?auth=' . $this->_token;

        // The fix ----
        if (strpos($path, ".json") > 0) {
            return $url . $path . '&auth=' . $this->_token;
        }else {
            return $url . $path . '.json' . $auth;
        }
    }

`
