### ISSUE TITLE
Too Sloooooow

### ISSUE THREAD

**Issue by zivoradmilekic** [ktamas77/firebase-php#34]
Hi guys. I tried really everything, but it still slow. I even implemented "use one curl for all quests" but it still slow. I have ten quests and I wait for page 7sec. which is too much. Please help, I need to finish project.

**Comment by alexsup** [comment]
It's hard to say unless you share your data structure.

Firebase response times are 99% linear to the number of bytes you read/write.

**Comment by ktamas77** [comment]
@zivoradmilekic could you please elaborate, share more details with us?

**Comment by mastef** [comment]
@zivoradmilekic might be ipv6 lookups, see https://github.com/ktamas77/firebase-php/issues/68#issuecomment-502921193
