### ISSUE TITLE
How to use print=silent

### ISSUE THREAD

**Issue by yankustefan** [ktamas77/firebase-php#38]
How do I properly use print=silent?

I wan't to make sure connections are immediately closed.
Or, how to make sure a connection is closed?

See:
[Improving Write Performance](https://www.firebase.com/docs/rest/guide/saving-data.html#section-rest-write-performance)

**Comment by ktamas77** [comment]
Query parameters are supported in version v2.1.0

https://github.com/ktamas77/firebase-php/releases/tag/v2.1.0

you can use

`$value = $firebase->get($path, array('print' => 'silent'));`
