### ISSUE TITLE
Is there a way to simulate a transaction?

### ISSUE THREAD

**Issue by mart92** [ktamas77/firebase-php#41]
Hi everyone, I'm searching for a way to simulate a transaction with Rest API. I seen that with this module there's no way to do it. What's the best way to simulate it? Thanks in advance! P.S. I'm sorry for my bad english.

**Comment by ktamas77** [comment]
The firebase REST api currently doesn't supports transactions:
https://github.com/ozgur/python-firebase/issues/20
