### ISSUE TITLE
Firebase->get() with void information

### ISSUE THREAD

**Issue by arturschaefer** [ktamas77/firebase-php#47]
Hi, guys.
I have a dictionary inside the Firebase.
Sometimes I want the information and, it returned a _NULL_ data, even in cases where the information exists in database.
To solve this problem I used an ugly solution:  a loop with 3 repetitions searching the information, and a condition when while the variable still empty, then do the loop. 

My main question is: there is a **better** way to do this?
The _"$firebase->setTimeOut($seconds);"_ with the more time will resolve?

**Comment by taykay08** [comment]
I think I'm having the same issue.  Every once in a while(rarely, but noticeably) when I fetch data I see the curl error "Empty reply from server".  I also see this issue popping up while attempting to update data.  For now I'll use a loop like you, but hoping someone knows of a better solution.  I actually tried to increase the timeout to 100 but it didn't seem to resolve the issue.
