### ISSUE TITLE
generate custom token

### ISSUE THREAD

**Issue by parthjdabhi** [ktamas77/firebase-php#52]
can i make custom token through this library, if yes how ?

Thank you!

**Comment by parthjdabhi** [comment]
@ktamas77 @llbbl @brianpilati  @craigrusso

**Comment by edesilets** [comment]
@parthjdabhi  I am 80% sure you can not make custom tokens through this package. This link 
[FireBase Create Custom Tokens](https://firebase.google.com/docs/auth/server/create-custom-tokens) will help point you in the right direction. [FireBase Token Generator for PHP](https://github.com/firebase/firebase-token-generator-php)

Personally on my project I ran out of time and had to hack my project, but you can use the javascript SDK on your front end and send back the users token and pass it in to the constructor as the second parameter. Ex:

 ```php
// Something like this.....
$firebase = new FirebaseLib(env('FIRE_DB_URL'), $request->cookie('token'));
```

I hope I've helped.
