### ISSUE TITLE
How can i add order by and equalTo

### ISSUE THREAD

**Issue by ithoangphuc** [ktamas77/firebase-php#58]
I use firebase-php of ktamas77. I try to get data with orderBy => 'data_id' (child) and equal to 'Test' but it report 

> "error" : "orderBy must be a valid JSON encoded path"

`$test = $initFirebase->get('/notification',array('orderBy' => 'data_id', 'equalTo' => 220));`

**Comment by VMitin** [comment]
Hey.  You must paste the data_id in the double quotes. 
My examlpe: 
`$fireBase->get(PUSH_PATH, array('orderBy' => '"status"', 'equalTo' => PENDING)`

And don't forget put the 
`".indexOn" : "status"`
on the firebase rules
