### ISSUE TITLE
Running too slow

### ISSUE THREAD

**Issue by ivent** [ktamas77/firebase-php#68]
Hello, the script works very slow to 7 seconds to perform each operation, I know that the response of the firebase is fast so I wonder how it does to improve the response speed performance of the script.

**Comment by salimbutex** [comment]
exact same issue. any ideas?

**Comment by ivent** [comment]
Hello, I have not made any improvements to my pho code but I still have a delay with regards to the library that needs to be solved. In javascript the updates are so fast that they seem to be instantaneous php should behave the same way or close to that rs

**Comment by mastef** [comment]
@ivent @selimonline I had some very slow consecutive requests and I don't recall how I resolved them, but try running the requests with : 
`curl_setopt($this->_ch, CURLOPT_VERBOSE, true);`
to see where it's hanging.

My getCurlHandler has the following added lines : 

```diff
+        curl_setopt($this->_ch, CURLOPT_HTTPGET, true); // <-- to reset CURLOPT_POSTFIELDS
         curl_setopt($this->_ch, CURLOPT_URL, $url);
         curl_setopt($this->_ch, CURLOPT_TIMEOUT, $this->_timeout);
         curl_setopt($this->_ch, CURLOPT_CONNECTTIMEOUT, $this->_timeout);
+        curl_setopt($this->_ch, CURLOPT_SSL_VERIFYPEER, false); // <-- set to false to speed up SSL connections ; do at your own risk
         curl_setopt($this->_ch, CURLOPT_FOLLOWLOCATION, true); 
         curl_setopt($this->_ch, CURLOPT_RETURNTRANSFER, true);
+        // curl_setopt($this->_ch, CURLOPT_VERBOSE, true); // <-- for debugging, turn off after you're done
         curl_setopt($this->_ch, CURLOPT_CUSTOMREQUEST, $mode);
+        curl_setopt($this->_ch, CURLOPT_HTTPHEADER, []); // <-- reset headers when switching from write to read
+        curl_setopt($this->_ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4 ); // <-- force ipv4, helps with servers that have ipv6 dns lookups misconfigured
```

@ktamas77 you might want to consider some of these.
