### ISSUE TITLE
How to upload image through firebase storage?

### ISSUE THREAD

**Issue by ivent** [ktamas77/firebase-php#70]
Hello, I would like to know if there is a plan to include uploading images through firebase storage, I had to implement the upload in javascript because of the lack of this resource in the lib but I would like to do it via php is it possible?

**Comment by Saketsuraj** [comment]
@ivent , did you find any solution?

**Comment by ivent** [comment]
Hi, I haven't used this api in a long time; so, i don't know how to answer, if it resolves, i'm using the same route.
