### ISSUE TITLE
Git push is removing firebase_php folder.

### ISSUE THREAD

**Issue by iit2011081** [ktamas77/firebase-php#73]
I have an application in which I installed this library and it was working fine. But when I push my application using git push firebase_php folder gets changed to something. When I go to my bitbucket dasboard it is showing firebase-php → fbfeefe84376 [fbfeefe84376]. I earlier had firebase jwt library so I thought git is getting confused with these two libraries. So I removed firebase jwt library but still it is showing same error.

**Comment by DragoTechInnovations** [comment]
Most of the times vendor folder is ignored by git as it is mentioned in `.gitignore`
This is so that you may install the version after cloning the files by running composer install or what ever is applicable.
