### ISSUE TITLE
Cannot use Database and Auth together

### ISSUE THREAD

**Issue by echosalik** [ktamas77/firebase-php#75]
I m getting this error:
`Fatal error: Cannot use Kreait\Firebase\Http\Auth as Auth because the name is already in use vendor\kreait\firebase-php\src\Firebase\Database.php on line 10`

But it doesn't make sense. The conflict comes from the Auth.php because there is already a Class with name Auth but the namespace is different for both, so it should not matter. Right?

Disabling line 10 on `Database.php` removes the error. Which is am using as a fix.

**Comment by ktamas77** [comment]
You are using a different library.
To use this library you need to install it with `composer require ktamas77/firebase-php`
