### ISSUE TITLE
firebase connection in php

### ISSUE THREAD

**Issue by gana549** [ktamas77/firebase-php#77]
hi.. i m gana actually i m trying to firebase connection php

i follow the https://firebase-php.readthedocs.io

'; $firebase = (new Factory) ->withServiceAccountAndApiKey($serviceAccount, $apiKey) ->withDatabaseUri('https://my-project.firebaseio.com') ->create(); ?>
but i got an error like

Fatal error: Uncaught Error: Call to undefined method Kreait\Firebase\Factory::withServiceAccountAndApiKey() in F:\xampp\htdocs\ganesh\index.php:23 Stack trace: #0 {main} thrown in F:\xampp\htdocs\ganesh\index.php on line 23

the method "withServiceAccountAndApiKey()" not present in factory class
so plz any one help me how to solve this issue

**Comment by harding13** [comment]
you're asking in the wrong place

this is the right one
https://github.com/kreait/firebase-php/issues
