### ISSUE TITLE
Setting value to 0 (number) is not possible

### ISSUE THREAD

**Issue by remixer-dec** [ktamas77/firebase-php#84]
When I'm trying to set a value to 0 with
```php
$firebase->set($path,0);
```
Firebase returns an error
```json
{ "error" : "No data supplied." }
```
And when I send it as a string "0", the value in the database also becomes a string.
For me it's not critical, but I think this is an important thing to notice.

**Comment by ktamas77** [comment]
Thank you, I'll look into this.
