### ISSUE TITLE
Credentials provided by firebase

### ISSUE THREAD

**Issue by ahmu83** [ktamas77/firebase-php#85]
The credentials provided by firebase are in the following manner **`var config = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: ""
};`** how can I translate them to the constants that are shown in the example (**DEFAULT_URL**, **DEFAULT_TOKEN** & **DEFAULT_PATH**)

**Comment by ktamas77** [comment]
DEFAULT_URL = $databaseURL
DEFAULT_PATH = <you can specify a prefix path here or leave it empty>
DEFAULT_TOKEN = apiKey
